python ./train.py \
    --model_dir=./mount/temp/cifar10/model/resnet.momentum.decay \
    --batch_size=128 \
    --save_interval_epochs=5 \
    --metric_eval_interval_steps=0 \
    --valid_interval_epochs=1 \
    --inference_interval_epochs=5 \
    --optimizer=momentum \
    --momentum=0.9 \
    --learning_rate=0.1 \
    --learning_rate_decay_factor=0.99 \
    --num_epochs_per_decay=1. \
    --num_epochs=500 \
    --save_interval_steps 10000
